### ISSUE TITLE
Question: Is it possible to use the first row as the title row?

### ISSUE THREAD

**Issue by fearphage** [bahmutov/console.table#10]
Is there a way to use the first row as the title row instead of printing the array indexes as the header?

Thanks in advance!

**Comment by bahmutov** [comment]
Would this be an array of arrays like this?
```js
[
  ['name', 'age'],
  ['max', 20],
  ['joe', 30]
]
```

**Comment by fearphage** [comment]
Yes, that is correct.

**Comment by bahmutov** [comment]
ok, try v0.7.0 - see the README for the example, title and items should be separate arguments
