### ISSUE TITLE
Doesn't work in Node.js 8

### ISSUE THREAD

**Issue by vitaly-t** [bahmutov/console.table#15]
I'm using Node.js 8.3 here, and the library doesn't work.

Calling `console.table` just doesn't outputs anything.

**Comment by bahmutov** [comment]
Hmm, I guess you would need to debug this and maybe submit a fix - I am mostly using Node 6 right now

**Comment by vitaly-t** [comment]
@bahmutov it doesn't work because Node.js 8 supports the new standard: https://developer.mozilla.org/en-US/docs/Web/API/Console/table

And you do this check: https://github.com/bahmutov/console.table/blob/master/index.js#L8, which in Node 8.x terminates the initialization always.

**Comment by vitaly-t** [comment]
So currently I use the work-around:

```js
delete console.table;
require('console.table');
```

**Comment by bahmutov** [comment]
I think an interesting solution would be to switch this `console.table` to take an option to override
the `console.table`. Something like
```js
require('console.table')({force: true})
```

**Comment by vitaly-t** [comment]
I think the right solution should be to verify the Node.js version, and make decision automatically.

As per the issue I opened in Node.js, current Node 8.4.0, `console.table` is there but does nothing. So there would be zero value in any `force` option.

**Comment by bahmutov** [comment]
Should work now
```
$ node
> console.table('foo', 'bar')
undefined
> require('.')
{}
> console.table('foo', 'bar')
foo
bar
undefined
> process.version
'v8.4.0'
> .exit
```

**Comment by bahmutov** [comment]
Version `0.9.0` has been published to NPM. The full release note can be found at [console.table/releases/tag/v0.9.0](https://github.com/bahmutov/console.table/releases/tag/v0.9.0).

**Tip:** safely upgrade dependency console.table in your project using [next-update](https://github.com/bahmutov/next-update)

**Comment by vitaly-t** [comment]
@bahmutov  It works in Node 8.4.0 fine now. Thank you!

Feel free to close the issue, because somehow I'm not allowed to do it here... 😕

**Comment by vitaly-t** [comment]
P.S. First though, see my comment in the code: https://github.com/bahmutov/console.table/commit/f5eb58e03c4c962a2d49e9a17ee8fc99b8517f31
